### ISSUE TITLE
Mark 1.1 as pre-release?

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/documentation#112]
Read the Docs wasn't building our documentation for some reason. It has started working now, but I noticed that it's now using the 1.1 branch as the "stable" release. See https://docs.citationstyles.org/en/stable/specification.html.

We could either rename the 1.1 branch to mark it as pre-release (see https://docs.readthedocs.io/en/stable/versions.html#versioned-documentation), or I can redirect https://docs.citationstyles.org/ to "1.0.1" instead of "stable" (although we probably link to "stable" in a bunch of places, so the former would be better).

cc @adam3smith, @bdarcus, @bwiernik

**Comment by bdarcus** [comment]
Whatever you think is best is fine with me. You have more experience with
this.

>

**Comment by rmzelle** [comment]
Per https://github.com/readthedocs/readthedocs.org/issues/3528, the cleanest option might be to add a "1.0.1" tag to the tip of the "1.0.1" branch.

**Comment by rmzelle** [comment]
Closing. Fixed by tagging the 1.0.1 branch with a "v1.0.1" (release) tag: https://github.com/citation-style-language/documentation/releases/tag/v1.0.1
