### ISSUE TITLE
Simplify cs:updated because hours/minutes/seconds are not relevant

### ISSUE THREAD

**Issue by cormacrelf** [citation-style-language/documentation#129]
It's a small pain point but the format allowed in `cs:updated` is an [xsd:dateTime](http://books.xmlschemata.org/relaxng/ch19-77049.html) when it should probably have been an [xsd:date](http://books.xmlschemata.org/relaxng/ch19-77041.html). One shouldn't have to look up xsd:dateTime and type in a bunch of zeroes and colons in the right order to make CSL validate. For a field that really, really does not need timestamp precision.

Simple solution: allow either. Then people can update with `2020-05-19`, much more human friendly.

**Comment by bwiernik** [comment]
See Dan's comment at the PR.
