### ISSUE TITLE
URL wrapping

### ISSUE THREAD

**Issue by atlascoder** [citation-style-language/documentation#137]
Hello!

Is this possible to add a rule for url wrapping? The rule that will define preferrable character for breaking url string.

Particularly, in Ukraine we have requirement to break URLs after '/' symbol. In example:
```
https://github.com/citation-style-language/documentation/issues/new
```
if to be broken - then to lines like:
```
https://github.com/citation-style-language/
documentation/issues/new
```

Thanks to all contributors - the CSL is a great tool!

**Comment by bwiernik** [comment]
This is something that really needs to be handled by the display program--the word processor, web browser, Pdf builder, etc. A program should not insert characters in the middle of a URL, so there isn't really anything in scope for CSL to handle here.

**Comment by atlascoder** [comment]
@bwiernik hah, I agree that this is responsibility of a displaying program. But it's usually made by plugins, eg for Word, and plugin can have such requirement from CSL and be able to make good text layout. Not by braking url, but by adding special symbols like hidden spaces https://stackoverflow.com/questions/40615559/is-there-an-invisible-hyphen-character-in-unicode-html

**Comment by bdarcus** [comment]
But the point is, such a plugin is running some CSL code (citeproc-js and
such), so it's up to that code to handle this. It shouldn't be configured
in a CSL style.

Right?

>

**Comment by bwiernik** [comment]
@atlascoder That's exactly the thing we _don't_ want to do. Adding characters into the middle of a URL will often break their resolution. For example, if we take this URL:
https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

and add a soft hyphen `¬` character (used to indicate optional line break points), the URL is broken:
https://developer.mozilla.org/¬en-US/docs/Web/CSS/hyphens
(same as: https://developer.mozilla.org/%C2%ACen-USen-US/docs/Web/CSS/hyphens)

Similarly, if we add a zero-width space `​`, the URL is also broken:
https://developer.mozilla.org/en-US/​docs/Web/CSS/hyphens
(same as: https://developer.mozilla.org/en-US/%E2%80%8Bdocs/Web/CSS/hyphens)

It is rarely safe to add characters to a URL. Line breaking in a URL needs to be controlled by the CSS style sheet for a webpage, the PDF generator, the word processor style sheet, etc. None of the safe approaches for controlling such behavior are things that CSL controls.

**Comment by atlascoder** [comment]
@bdarcus but what is difeerence between <text prefix="."/> and <text word-frap-after="/"/>? for the plugin?

I see this simple: CSL has attribut, plugin forms output. Does it work in another way?

**Comment by atlascoder** [comment]
@bwiernik you are right, but.. The real URL and the text of the link - are separate things in most of formatted text displaying software. So, soft hyphens, or hidden space can be added to visible link text, but real URL that is associates - is still the same.

**Comment by atlascoder** [comment]
@bwiernik the single case where it will break URL - it's pure text, where text and link string are the same..

**Comment by atlascoder** [comment]
I don't argue, just propose to consider a feature. Personally me, I guess that this is related not only for Ukrainian stadard DSTU 8302:2015... It would be useful

**Comment by bwiernik** [comment]
Inserting symbols into the text that appears with the link breaks the ability to copy and paste the link, which is the whole point of displaying the URL text. This isn’t something that CSL can control.
