### ISSUE TITLE
Tag 1.0.2 docs as stable/v1.0.2

### ISSUE THREAD

**Issue by larsgw** [citation-style-language/documentation#138]
Currently the new docs are only accessible by selecting the master branch on https://docs.citationstyles.org/. The default branch is stable which still points to `v1.0.1` and although previous versions (including `v1.0`) are available by version number (like https://docs.citationstyles.org/en/v1.0.1/specification.html), this version is not yet. I don't know exactly how the docs deployment is set up but I think at least a tag named `v1.0.2` on 2ae74b2c27f31ecc68c9cfa1adb2e634cb1d626f would be nice.

Edit: before it is tagged perhaps we should replace mentions of `1.0.1` with `1.0.2`.

**Comment by larsgw** [comment]
It's a bit unfortunate because I *just* created a mapping (and finished two different ones) using `v1.0.1` still. I missed the entire release (😞) and never realized due to the docs website.

**Comment by bwiernik** [comment]
We have been waiting for a few things to be in place with the styles repo.

**Comment by adam3smith** [comment]
OK. @bdarcus @denismaier @rmzelle everyone on board with December 1? 
Could we create one master checklist issue of what needs to happen on December 1 and before? I feel like we've talked about this a bunch, but not sure if it's all in one place (certainly not in a place I know)

**Comment by bwiernik** [comment]
The ReadTheDocs page now displays 1.0.2 as stable

**Comment by customcommander** [comment]
Congrats on the 1.0.2 release ;)

I noticed that the website still has a lot of hardcoded links to the 1.0.1 specs. Is this something that you have planned to address or will you accept a pull request?

**Comment by adam3smith** [comment]
Pull request would be great

**Comment by bdarcus** [comment]
Do we have a "latest" version I'd/link we can use?

**Comment by adam3smith** [comment]
For the specs? https://docs.citationstyles.org/en/stable/specification.html

**Comment by customcommander** [comment]
See https://github.com/citation-style-language/citation-style-language.github.io/pull/47 — Not too sure; first time I contribute to this repo.
