### ISSUE TITLE
Can a number be rendered with <text>?

### ISSUE THREAD

**Issue by customcommander** [citation-style-language/documentation#143]
Hi,

The `variable` attribute of a `<text>` must be set to a standard variable name. Unless I am mistaken standard variables are only a subset of all variables.

![Screenshot 2021-07-05 at 10 53 45](https://user-images.githubusercontent.com/681975/124454171-1141a800-dd80-11eb-8ea6-45205d6a45c1.png)

However in the `<number>` specification it seems like we have the option of displaying a number either as a number or as text:

![Screenshot 2021-07-05 at 10 54 32](https://user-images.githubusercontent.com/681975/124454353-4cdc7200-dd80-11eb-8209-78f9e98a3ca2.png)

But if that is the case then shouldn't `<text>` says something like _"must be set to a variable name"_ i.e. any variable can do as opposed to just a standard variable.

**Comment by bwiernik** [comment]
The 'standard variables' are the variables that can be rendered with `text`. It includes the 'number variables' as a subset. https://github.com/citation-style-language/documentation/blob/master/specification.rst#standard-variables

**Comment by bwiernik** [comment]
The contrast of 'standard' variables is to name or date variables (and in the future, title variables).

**Comment by customcommander** [comment]
Omg! Didn't notice, sorry.

Just to clarify: name and date variables aren't a subset of standard variables?

**Comment by bwiernik** [comment]
Yes, ‘standard’ variables are the ones represented by a single flat text field. Names have structured name parts and dates have date parts.
