### ISSUE TITLE
Include (default) character to be used as range delimiter in specification

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/documentation#15]
A [thread ](http://forums.zotero.org/discussion/18480/endash-instead-of-hyphen-in-collapsed-numeric-citations/#Item_5) on the Zotero forums has raised an issue concerning the character used as range delimiter.

Currently, based on discussions on xbiblio-devel, citeproc-js and the test suite assume en-dash as the delimiter for collapsed ranges. This applies to page numbers, and also to citation numbers and year-suffixes.

The thread linked above asks that the delimiter be made configurable. Before (or when or after) that happens, the current behavior should be documented in the spec. Rintze has asked for a ticket to be opened, and here it is. :)

The sister to this ticket in the schema tracker is [here](https://github.com/citation-style-language/schema/issues/56).

**Comment by adam3smith** [comment]
This is superseded by the introduction of  ```page-range-delimiter``` in CSL 1.0.1
