### ISSUE TITLE
CSLADMIN : cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Debo1594** [citation-style-language/documentation#152]
Does any one knows about citation style language (CSL) we are using one of our project and now we are planning for application server migration from HP-UX to RHEL8. So, we need to know about how we install the CSL and where we can get it. We could not able to find much information from google. From our old HP_UX server we used CSL Version 1.3 but we don't know how to get it for RHEL 8. Existing CSLADMIN from HP-UX server is not compatible for RHEL8 server. Because, we transferred the file from HP-UX to RHEL8 and getting below error after configuring the same as per RHEL8 server and compiling. 

csladmin: cannot execute binary file: Exec format error

**Comment by denismaier** [comment]
Are you sure you're asking at the right place?

**Comment by Debo1594** [comment]
Just I saw that couple discussion ongoing here about CSL. So, I posted the question to get some help from the forum.

**Comment by denismaier** [comment]
The discussion here are about the schema of the language. What's the context of your specific question?

**Comment by Debo1594** [comment]
Is there any CSL software package is available for RHEL8. Because, the framework or package we have in hp-ux is not compatible in linux. this csl is being used to compile and generate the pro*c source code.

**Comment by bdarcus** [comment]
You're in the wrong place. There's no software here; certainly not proc*c source code.
