### ISSUE TITLE
How to define an in-text format for HTML citations?

### ISSUE THREAD

**Issue by cboettig** [citation-style-language/documentation#33]
Hi CSL folks,

I would like to define a CSL file in which the in-text format includes a link to the resource. Can this be done in CSL by say, modifying the layout element appropriately?  I cannot figure out how to use a variable in the prefix/suffix.

I imagine a `<citation>` element looking something like this:

``` xml
 <layout prefix="(<a href='URL'>" suffix="</a>)" delimiter="; ">
          <text macro="author-short"/>
          <text macro="issued" prefix=" "/>
</layout>
```

but cannot see how to get URL value from something like `<text macro="url">` into the prefix.  

Given the importance of web-based formats and the ease of using CSL to generate citations in markdown and html documents with tools such as pandoc, it seems natural that individuals would want to style in-text citations not only to reflect journal norms of author surnames etc, but include such features as actual links, perhaps add `title` attributes for mouse-over effects, and so forth.  If this is not possible in the current implementation, is this something CSL might address in the future?

**Comment by denismaier** [comment]
What's the status of this here? In any case, that is not really related to the specs. Closing for now.

**Comment by bdarcus** [comment]
This is associated with #76, which I think we need to resolve for 1.1.
