### ISSUE TITLE
Bad “Edit on GitHub” link

### ISSUE THREAD

**Issue by spl** [citation-style-language/documentation#37]
On http://docs.citationstyles.org/en/stable/specification.html , the link is https://github.com/citation-style-language/documentation/blob/origin/1.0.1/specification.txt . If you take out `origin/`, it would be better; however, I think the preferred link would be https://github.com/citation-style-language/documentation/blob/master/specification.txt for the HEAD instead of the release.

**Comment by rmzelle** [comment]
That link is automatically generated by Read the Docs. Might be fixed by https://github.com/rtfd/readthedocs.org/pull/1365, so hopefully this will be automatically fixed the next time the files are processed.

And "stable" is specifically linked to "1.0.1", since that's the latest CSL release ("master" is the pre-release development branch), so that's correct.

**Comment by spl** [comment]
I understand that 1.0.1 is the version shown, but you should also consider
which version you want people to edit. I expect you would prefer people to
use the latest version, which may have changes, even if that is not
released. I've never seen another GitHub-based project link to a non-master
branch for forking. But in the end, it's a minor thing and certainly boils
down to personal preference.

**Comment by rmzelle** [comment]
Well, most readers will be users of the spec, not developers of the CSL specification, so we shouldn't send folks to "master". It might even be better to hide the link altogether.

**Comment by spl** [comment]
> Well, most readers will be users of the spec, not developers of the CSL specification, so we shouldn't send folks to "master".

If someone wants to edit (indicated by clicking on the link), that person is presumably more a (potential) contributor than a reader. And people who want to edit will want (I would expect) the latest version of the spec. This might help avoid different people contributing identical or conflicting changes.

> It might even be better to hide the link altogether.

Possibly. You could put a different link in the text itself, with more documentation about contributing. But I do think it's a good idea to advertise that you welcome contributions (assuming you do) in some form or another.

**Comment by rmzelle** [comment]
> But I do think it's a good idea to advertise that you welcome contributions (assuming you do) in some form or another.

Yeah, but maybe the "Edit on GitHub" link isn't the best way for this. I guess the best metadocumentation we currently have is http://citationstyles.org/developers/. Also e.g. the primer has a note on feedback (http://docs.citationstyles.org/en/stable/primer.html#feedback).

For the release branches, we really only want to correct grammatical and typographic errors. I guess we would take outside contributions for more significant rewrites for the master branch (e.g. to clarify certain sections), but traditionally we have had very few outside contributions. And if we're talking about describing new CSL features, people would already have to be familiar with our GitHub setup anyway.

**Comment by rmzelle** [comment]
Closing because the original issue was solved. Created a new issue for adding a README to the repository, to give readers instructions on how to provide feedback: https://github.com/citation-style-language/documentation/issues/44
