### ISSUE TITLE
No locale fallback specified for fr and es

### ISSUE THREAD

**Issue by brechtm** [citation-style-language/documentation#48]
I would assume `fr-CL` to fallback to `fr-FR` and `es-CL` to `es-ES`, but these are not listed in the [table in the CSL spec](http://docs.citationstyles.org/en/stable/specification.html#locale-fallback).

**Comment by rmzelle** [comment]
Thanks. Looks like we should add "es-MX" and "es-CL" as secondary dialects with "es-ES" as primary for Spanish, and "fr-CA" as secondary dialect with "fr-FR" as primary dialect for French.

As long as we don't have a dedicated "fr-CL" CSL locale file, we wouldn't add it to the fallback table in the CSL spec, though. Do you have users asking for it?

(and in general, while I think it's good to formalize fallback locales in the spec, in most cases it's rather obvious which locale is primary and which are secondary, and the CSL spec table doesn't really need to be all-inclusive)

**Comment by rmzelle** [comment]
(or did you mistype "fr-CA" as "fr-CL"?)

**Comment by rmzelle** [comment]
Oh, and it might not be documented anywhere, but https://github.com/citation-style-language/locales/blob/master/locales.json should define all primary locales.

**Comment by brechtm** [comment]
Yes, I meant "fr-CA".

Thanks for the pointer on locales.json. I suppose I can count on that file being kept up to date? I'll use that instead of defining the mappings in my source code. Perhaps it's a good idea to mention this file in the CSL specification docs?

**Comment by rmzelle** [comment]
We don't get new locales very often (the last was in 2015), but yeah, we have automatic Travis CI testing to make sure that locales.json is valid JSON and defines a primary dialect for all languages in the locales repo, so it should be pretty robust (https://github.com/citation-style-language/locales/blob/master/spec/repository_spec.rb).

**Comment by rmzelle** [comment]
> Perhaps it's a good idea to mention this file in the CSL specification docs?

Yes, or somewhere else in our project documentation.

**Comment by rmzelle** [comment]
(I'll leave this open so I won't forgot to update the fallback table in the spec)

**Comment by customcommander** [comment]
@rmzelle @brechtm Please see PR #56
