### ISSUE TITLE
original-author

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/documentation#55]
The specification currently states that the purpose of `original-author` is unknown. It's currently only used by four unique styles (and about a dozen variations on those). Two of those list `original-author` among a list of all of the other creator types and so don't use it really. The other two use it in a hack-y either to create an "inventor" term or to be used as a "series editor" (for some reason). 

I've thought about this a bit, and the only purpose of an "original author" variable that I can think of is for musical recordings or other performances, where one might cite the original performer or songwriter of a work, in addition to the current performer.

**Comment by bwiernik** [comment]
It might also be used for the creator of a television series. For example, APA asks that series creators be cited as Jones, S. (Creator) or Jones, S. (Creator and Producer), etc. Though mixing these uses might be problematic.

**Comment by zaw-shinoto** [comment]
Related to [this thread](https://github.com/citation-style-language/documentation/issues/42)? 

> Name variable 'original-author' is described as '?' #42
