### ISSUE TITLE
Different format for citations in running text and within parentheses

### ISSUE THREAD

**Issue by jalvesaq** [citation-style-language/documentation#57]
Is it possible to differentiate citations in running text from citations within parentheses?

In the webpage [In-Text Citations](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/in_text_citations_author_authors.html) the first example is:

```
Research by Wegener and Petty (1994) supports...
(Wegener & Petty, 1994)
```

That is, outside of parentheses, we should use "and" to separate the name of the last author from the name of the first author while within parentheses we should use "&" to do the same. The above example is in the APA style. If the citations were following the style defined by the Brazilian Association of Technical Norms (ABNT, which is hegemonic in Brazil) the difference would be more visible because it requires the names of authors in upper case, but only within parentheses:

```
Research by Wegener and Petty (1994) supports...
(WEGENER; PETTY, 1994)
```

**Comment by rmzelle** [comment]
CSL 1.0.1 doesn't support this. Right now, CSL styles only define the parenthetical version, and leave it to the CSL processor (the software that understands and processes CSL styles and item metadata) to create a running-text version based on the parenthetical version. You would then typically write out the part before the parentheses by hand. See https://citationstyles.org/authors/#suppress-author for some more information.

We're aware that this solution has some drawbacks, so a future version of CSL might allow both types of citations to be explicitly defined. See also https://github.com/citation-style-language/schema/issues/141.
