### ISSUE TITLE
Fallback for long-ordinal terms

### ISSUE THREAD

**Issue by customcommander** [citation-style-language/documentation#58]
Hi,

From the doc at http://docs.citationstyles.org/en/1.0.1/specification.html#number

> Long ordinals are defined with the terms “long-ordinal-01” to “long-ordinal-10”, which are used for the numbers 1 through 10. For other numbers “long-ordinal” falls back to “ordinal”.

I have two questions:

1. What is the default match attribute for long-ordinal terms? Is it "whole-number"?
2. Should you always fallback to "short" ordinals or only if the number to ordinalize is bigger than 10?

Thanks!

**Comment by rmzelle** [comment]
> * What is the default match attribute for long-ordinal terms? Is it "whole-number"?

Yes, I think the unspoken assumption has always been that the long-ordinal terms are only relevant to their respective numbers.

> * Should you always fallback to "short" ordinals or only if the number to ordinalize is bigger than 10?

It wouldn't hurt to always fall back to "short" ordinals. The CSL locale file template we use for all languages should have "long-ordinal-xx" terms for numbers 1-10, but there might be cases where people use a CSL locale file without some of these terms.

**Comment by customcommander** [comment]
Would you accept a PR to document these assumptions?

**Comment by rmzelle** [comment]
We'll probably tweak it a bit, but sure!

**Comment by customcommander** [comment]
@rmzelle See #60
