### ISSUE TITLE
Additional locator types

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/documentation#62]
Current locator types are:
page
book
chapter
column
figure
folio
issue
line
note
opus
paragraph
part
section
sub-verbo
volume
verse

There are a few additional common locator types that would be good to add:
table
equation
appendix
supplement

There are perhaps others as well, but I can't think of any at the moment. (cf. https://forums.zotero.org/discussion/comment/326399#Comment_326399)

**Comment by rmzelle** [comment]
(it's nowadays possible to transfer issues to other repositories; see https://help.github.com/articles/transferring-an-issue-to-another-repository/; this issue has been superseded by https://github.com/citation-style-language/schema/issues/166)

**Comment by bwiernik** [comment]
Sorry, didn't realize that was possible!

**Comment by rmzelle** [comment]
It's a rather new feature (haven't used it yet): https://twitter.com/github/status/1057678791764467712
