### ISSUE TITLE
What is the expected behaviour when dates are invalid

### ISSUE THREAD

**Issue by customcommander** [citation-style-language/documentation#63]
Good morning,

According to this [test suite](https://github.com/citation-style-language/test-suite/blob/ad158b293171ec6215e9a5e97e9dab262073ac19/processor-tests/humans/date_VariousInvalidDates.txt), when a date is invalid (e.g. `date-parts` contains `[1965, -1, 1]`) the `<date>` element should not render anything. While it makes sense to me, I just wanted to confirm with you whether that is the expected/appropriate behaviour.

As an aside, I do not understand why `Date: (Spring)` is an expected output. If you could shed some light on this, that would be much appreciated.

Thanks!

@rmzelle @adam3smith 

```
>>===== MODE =====>>
citation
<<===== MODE =====<<



>>===== RESULT =====>>
Date: (); Date: (Spring); Date: (Spring); Date: ()
<<===== RESULT =====<<


>>===== CSL =====>>
<style 
      xmlns="http://purl.org/net/xbiblio/csl"
      class="note"
      version="1.0">
  <info>
    <id />
    <title />
    <updated>2009-08-10T04:49:00+09:00</updated>
  </info>
  <citation>
    <layout delimiter="; ">
      <text value="Date: ("/>
      <date variable="issued">
        <date-part name="month" form="long" strip-periods="true"/>
      </date>
      <text value=")"/>
    </layout>
  </citation>
</style>
<<===== CSL =====<<


>>===== INPUT =====>>
[
    {
        "id": "ITEM-1", 
        "issued": {
            "date-parts": [
                [
                    1965, 
                    -1, 
                    1
                ]
            ]
        }, 
        "type": "book"
    }, 
    {
        "id": "ITEM-2", 
        "issued": {
            "date-parts": [
                [
                    1965, 
                    13, 
                    1
                ]
            ]
        }, 
        "type": "book"
    }, 
    {
        "id": "ITEM-3", 
        "issued": {
            "date-parts": [
                [
                    1965, 
                    17, 
                    1
                ]
            ]
        }, 
        "type": "book"
    }, 
    {
        "id": "ITEM-4", 
        "issued": {
            "date-parts": [
                [
                    1965, 
                    60, 
                    1
                ]
            ]
        }, 
        "type": "book"
    }
]
<<===== INPUT =====<<
```

**Comment by adam3smith** [comment]
@fbennett would be in a better position to speak to the (Spring) part -- that's presumably how citeproc-js understands months from 13-25(?), but there's nothing in the CSL specifications on this.

As for the main question: I would be more restrictive here and that's also what the test shows: a `date-parts` element is rendered as empty if it is invalid, but not the entire date. E.g. 
``` 
<date variable="issued">
        <date-part name="year"/>
      </date>
```

should print `1965`, not empty, for `ITEM-1` above.

**Comment by rmzelle** [comment]
See also https://github.com/Juris-M/citeproc-js/issues/61

**Comment by adam3smith** [comment]
(though that doesn't explain 17=Spring? Does citeproc just restart counting?)

**Comment by customcommander** [comment]
> As for the main question: I would be more restrictive here and that's also what the test shows: a `date-parts` element is rendered as empty if it is invalid, but not the entire date

I missed that somehow. Thanks for the clarification; it makes sense.

**Comment by adam3smith** [comment]
Closing this, happy for you to open new issues if other questions come up.

**Comment by customcommander** [comment]
Since I'm here can you have a look at my two outstanding pull requests perhaps? #60 #59 Thanks.

**Comment by adam3smith** [comment]
I'm fine with this, but documentation is @rmzelle 's baby, I'll let him merge those.
