### ISSUE TITLE
Specification errata

### ISSUE THREAD

**Issue by fbennett** [citation-style-language/documentation#65]
I've posted a response to [a thread](https://discourse.citationstyles.org/t/should-if-else-blocks-use-the-delimiter-from-a-parent-group/1511/9?u=frank_bennett) by @cormacrelf on CSL Discourse in which he raises questions over some of the language in the CSL Specification. The issue should be thrashed out further on Discourse to be sure there is consensus, but I'll put down a marker here on portions of the spec that I think could justifiably be amended without a version increment.

The main item is the [classification of `cs:choose` as a "rendering element"](https://github.com/citation-style-language/documentation/blob/2f6161950734da35fe0538ed5b6f6da0be260136/specification.txt#L1392). The history is laid out in the comment linked above, but the short version is that this appears to be a change made in an early draft of CSL 1.0.1, the implications of which (for the treatment of inherited delimiters) were not clear at the time.

A second issue is [this sentence](https://github.com/citation-style-language/documentation/blob/2f6161950734da35fe0538ed5b6f6da0be260136/specification.txt#L1369) in the **Group** description:

> "``cs:group`` may carry the ``delimiter`` attribute to separate its *child elements*, as well as ``affixes`` and ``display`` attributes (applied to the output of the group as a whole) and ``formatting`` attributes *(transmitted to the enclosed elements)*." (emphases added)

Charles Parnot noted in 2012 that "child elements" here intends to refer to descendants, and Sylvester Kiel noted in 2014 that "transmitted to the enclosed elements" is not the intended behavior. As these interpretations were agreed at the time, an amendment along those lines would make it clear that current implementations have not arbitrarily diverged from the specification.

**Comment by fbennett** [comment]
I see also that Sylvester Kiel posted a pull request (#34) to amend the spec language five years ago. His PR still has no conflicts against master, and could be adopted directly.

**Comment by rmzelle** [comment]
> The main item is the [classification of `cs:choose` as a "rendering element"](https://github.com/citation-style-language/documentation/blob/2f6161950734da35fe0538ed5b6f6da0be260136/specification.txt#L1392).

See also https://github.com/citation-style-language/styles/pull/4154#discussion_r296462827 (where I agree that `<choose/>` should show some atypical behavior for a rendering element).

**Comment by bdarcus** [comment]
So we have this and #34, which we need to close. I'm confused, so not sure what we want to do.

**Comment by bwiernik** [comment]
From @fbennett in https://github.com/citation-style-language/documentation/pull/34:
> * `cs:choose` itself should not be treated as a "rendering element;" and
> * formatting attributes on `cs:group` should be applied to the group as a whole, and not "transmitted" to its children.
> 
> Styles in the CSL repository are based on these assumptions.

I think we can leave `cs:choose` as a rendering element. That seems useful for being able to say: wherever you can use `cs:text`, you can use `cs:choose`. What needs to be clarified is the behavior of the `delimiter` attribute for `cs:choose` (and perhaps makes it clear `cs:macro` does not have this)

`cs:choose` can be a child of:
1. macro
1. layout
1. group
1. substitute

`macro` cannot have `delimiter` set, but `layout`, `group`, and `substitute` (inherited from parent `names`) can. 

`choose` should inherit delimiters when they are set on layout, group, or substitute. I'll open a PR.

**Comment by fbennett** [comment]
If it's convenient to call it a rendering element, but it needs to be made clear that parent delimiters are passed through it and its child condition elements transparently, to avoid the result that leads off the discussion in the [Discourse thread](https://discourse.citationstyles.org/t/should-if-else-blocks-use-the-delimiter-from-a-parent-group/1511).

**Comment by bwiernik** [comment]
See the PR

**Comment by denismaier** [comment]
> `macro` cannot have `delimiter` set,

By the way, why is that? Couldn't we allow that if macros are "encapsulated", as you call it?

**Comment by bwiernik** [comment]
`macro` just doesn't have a delimiter. Its only attribute is name. That's fine. If someone wants an attribute, they can use a `group`.

**Comment by denismaier** [comment]
> `macro` just doesn't have a delimiter. Its only attribute is name. That's fine. If someone wants an attribute, they can use a `group`.

Yes, but if `macro` is "encapsulated" anyway, it sort of acts like an implicit group, right? If so, we could also just allow delimiters...

**Comment by bwiernik** [comment]
Essentially what you're arguing is that `macro` should just be named `group`. That would eliminate a line of code, sure, but I do think it aids style readability to have the only attribute on `macro` be `@name`. I don't have very strong feelings about, but I don't see much benefit to changing existing behavior.

**Comment by denismaier** [comment]
Good for me. I was just wondering if there was a specific reason not to do this in the first place...
