### ISSUE TITLE
CSL version 1.0.1 insists on CSL version="1.0"

### ISSUE THREAD

**Issue by i3games** [citation-style-language/documentation#69]
In Section "XML Declaration":

> The CSL version of the style. Must be “1.0” for CSL 1.0-compatible styles.

This also affects the style checker https://github.com/citation-style-language/csl-validator.

![Screenshot 2020-02-07 at 12 14 56](https://user-images.githubusercontent.com/830492/74025429-34f29a00-49a4-11ea-9289-bba62ae3bc5c.png)

**Comment by rmzelle** [comment]
@i3games, I realize it looks a bit weird, but this was done on purpose.

CSL 1.0.1 is fully backwards-compatible with CSL 1.0, that is, all valid CSL 1.0 styles will also validate against the CSL 1.0.1 schema.

If we had started using `version="1.0.1"` for CSL 1.0.1 styles, we had to pick one of these options:

* If we only allowed `version="1.0.1"`, CSL 1.0 styles would no longer validate against the CSL 1.0.1 schema
* If we allowed `version="1.0.1"` or `version="1.0"`, we could bifurcate the entire schema so it evaluates styles against the original CSL 1.0 schema if a style uses `version="1.0"`, or the CSL 1.0.1 schema if a style uses `version="1.0.1"`. This would have added a lot of complexity to the schema, if it's technically feasible at all.
* Alternatively, we could allow `version="1.0.1"` or `version="1.0"`, and just always validate the styles against the CSL 1.0.1 schema. However, this wouldn't throw errors for CSL 1.0 styles that use CSL 1.0.1 features.

So all in all, we found it simpler to just use `version="1.0"` for all CSL 1.0.x styles.
