### ISSUE TITLE
processor instruction: extract CSL variables from `note`

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/documentation#97]
citeproc-js has behavior to extract CSL variables from the top of `note` (which is **Extra** in Zotero and **Note** in Mendeley). This behavior was implemented originally to facilitate sync-compatibility between Zotero and Jursim (then MLZ), but it has emerged as a really useful way for users of GUI applications to be able to access fields and types that the application doesn't provide. I think it might be useful to add this extraction behavior to the spec formally.

**Comment by denismaier** [comment]
Good idea, yes. So you think thus is also relevant for a other citeprocs? If I use pandoc, I can enter fields in the yaml file without using this cheater syntax.

**Comment by dhimmel** [comment]
It would be nice to have an official way to store additional / extra fields that are not part of the spec.

For Manubot, we support extra variables in `note`. [Parsing code here](https://github.com/manubot/manubot/blob/47b03e0c202e6a0561e6548ba08a4ad790f56eee/manubot/cite/csl_item.py#L194-L210). We support the citeproc-js "cheater syntax" [described here](https://github.com/Juris-M/citeproc-js-docs/blob/93d7991d42b4a96b74b7281f38e168e365847e40/csl-json/markup.rst#cheater-syntax-for-odd-fields).

But if support for extra fields becomes official, I think it's much preferable to have a JSON native way of specifying these fields. For example you could just allow the following in any CSL JSON Item:

```yaml
extras:
  my-field: I can have anything here
  my-other-field: null
```

The whole point of using something like JSON is that you can abstract all of the serialization to it. The variables in `note` "cheater syntax" is a hack because there is no `extras` field... seems like the best longterm solution is to provide a solution so the hack is no longer needed.

**Comment by bdarcus** [comment]
How is this better than allowing optional (possibly prefixed) extension
fields in the actual data representation?

**Comment by bwiernik** [comment]
I'm not sure exactly what you are responding to @bdarcus. My concern is mostly how users of GUI applications (rather than directly editing or constructing CSL-JSON) could add additional variables that are not provided by the application.

**Comment by bdarcus** [comment]
The title says "processor instructions."

**Comment by dhimmel** [comment]
> My concern is mostly how users of GUI applications (rather than directly editing or constructing CSL-JSON) could add additional variables that are not provided by the application.

Important use case I hadn't considered.

Are these GUIs designed for CSL JSON editing or are they for other metadata formats like Zotero data? If it's for other formats, perhaps it'd be best to convert the "cheater syntax" to JSON syntax upon export to CSL JSON? If the GUI is designed to edit CSL JSON directly, it seems reasonable that the GUI could support defining extra fields (once we establish a standard).

The job of CSL processors is simplified if they don't have to deal with parsing notes. Also the cheater syntax is really limited. No multiple levels.

**Comment by denismaier** [comment]
@bwiernik was talking about Zotero or Mendeley. These tools provide certain fields in their UI, but users might need access to other fields. Currently, you can't enter `original-publisher` via UI fields, but you can use the cheater syntax in Zotero's `Extra`  field.

**Comment by denismaier** [comment]
>  @dhimmel and I were just pointing out we wouldn't want to do that, because we can simply address the limitation the hack was working around in the first place. If we're only talking about how Mendeley and Zotero handle that data in their GUI, I think that's out of scope for CSL. If we add the extension mechanism, that shouldn't be necessary. And more to the point, I'd argue it's not a very good hack in the GUI apps. Probably better would be to allow structured key-value extension fields, to avoid things like syntax errors.

Not that'd be oppossed to this idea, but isn't that something we can hardly influence as you say yourself?

**Comment by bwiernik** [comment]
I don't really care about outside-of-CSL custom variables; that is outside of the scope of this proposal. (I am personally opposed to those existing to avoid the incompatible-data proliferation problem that BibTeX has.) What I care about is specifying valid CSL variables when there isn't a proper field in the application to hold that variable. For example, Zotero or Mendeley don't have a field for Original Publisher. But, because of citeproc-js's current behavior, they can access this variable by entering it into a GUI field (e.g., the "Note" field in Mendeley). 

Yes, it would be good for the application to extract these variables into the CSL-JSON when constructing it (the Better BibTeX plugin in Zotero does this, for example), but that is out of our control. This provides a application-agnostic pathway to user flexibility. It's been in play in citeproc-js for years, and it seems to work well.

(The cheater syntax can support multiple levels (a variable can be entered like a javascript object), but all CSL variables can also be entered as flat key-value pairs (e.g., names as `Family || Given`, dates in as `YYYY-MM-DD/YYYY-MM-DD`).)

**Comment by bdarcus** [comment]
> What I care about is specifying valid CSL variables when there isn't a proper field in the application to hold that variable.

Fair enough; I agree that's an issue someone should solve.

But why is this _our_ problem; to address in the spec no less?

**Comment by bwiernik** [comment]
> But why is this our problem; to address in the spec no less?

One of the major citeprocs already defines a behavior that addresses the problem in a reasonable way. I don't see that going away, and it would be nice to standardize the behavior.

**Comment by dhimmel** [comment]
> What I care about is specifying valid CSL variables when there isn't a proper field in the application to hold that variable. For example, Zotero or Mendeley don't have a field for Original Publisher. But, because of citeproc-js's current behavior, they can access this variable by entering it into a GUI field (e.g., the "Note" field in Mendeley).

On one hand, it would be nice for the Zotero and Mendeley CSL JSON exporters to parse their notes to see if parts of the note should be converted to CSL JSON fields. FWIW, I've had some success getting Zotero CSL export features implemented by opening issues, and I imagine my success would be higher if I had the expertise to submit PRs. So this route is viable.

On the other hand, dealing with multiple CSL JSON exporters might be a pain, especially if their behavior has to frequently change in the future. In these cases, I see the benefits of the note extraction happening on the citeproc side.

These two options are not mutually exclusive.

If we do decide to go ahead with CSL variables in notes, are we happy with the current citeproc-js syntax?

> I don't really care about outside-of-CSL custom variables; I am personally opposed to those existing to avoid the incompatible-data proliferation problem that BibTeX has.

Custom variables are inevitable and required for certain use cases. We use the note cheater syntax in Manubot to store variants of id ([example](https://github.com/manubot/manubot/blob/47b03e0c202e6a0561e6548ba08a4ad790f56eee/manubot/cite/tests/test_csl_item.py#L110-L126)). Since custom variables are inevitable, I think it's best to consider the most effective and least problematic method for storing them. I agree this is a largely distinct issue from the spec-variables in note extraction.

**Comment by dhimmel** [comment]
> (The cheater syntax can support multiple levels (a variable can be entered like a javascript object), but all CSL variables can also be entered as flat key-value pairs (e.g., names as `Family || Given`, dates in as `YYYY-MM-DD/YYYY-MM-DD`).)

That is more flexible than I realized. Of course the cost of that flexibility is the parsing rules are more complicated. Furthermore, the JSON Schema won't be able to encode these parsing rules. I wonder if it would make sense to have reference implementations for different languages. Or possibly a utility that de-notes CSL JSON variables so not every processor has to implement this.

**Comment by bdarcus** [comment]
It seems part of the impetus of this is motivated by uncertainty about what Zotero, in particular, may or may not do.

Rather than speculate, why not simply ask?

@dstillman (cc @retorquere) - is there any reason we can't ask Zotero to parse the `extra` data and export it to proper json fields? So, instead of this:

``` json
"note": "source: twitter.com",
```
... to something like this:

``` json
"source": "twitter.com",
```
So for all those keys that exist in CSL, but don't have dedicated fields in Zotero, convert to the csl json; everything else dump in some `extra` object.

**Comment by bdarcus** [comment]
> > But why is this our problem; to address in the spec no less?
> 
> One of the major citeprocs already defines a behavior that addresses the problem in a reasonable way. I don't see that going away, and it would be nice to standardize the behavior.

But it's a hack!

**Comment by denismaier** [comment]
I think the general case here is beyond dispute. The question is just how to best deal with that situation. I see a couple of options:

1. Zotero et al let users add custom fields

2. Zotero et al add one additonal field `raw json`/`raw yaml`

3. Request from Zotero et al to implement the parsing mechanism

4. Formalize the note parsing hack as expected processor behaviour

5. Do nothing about it at all

Solution 1 would obviously be best, but maybe also the hardest to implement.

One question certainly is if this is at all relevant for other citeprocs. Like, if I use pandoc with pandoc-citeproc, I'll either create my yaml bibliographic data manually or export them with Zotero BBT. (I don't know if there is a reliable workflow with Mendeley.) Of course, there are also other citeprocs, but those aren't typically used by end-users, and their data does not come from the usual suspects. So, maybe we can ignore those for the moment.

**Comment by denismaier** [comment]
> So for all those keys that exist in CSL, but don't have dedicated fields in Zotero, convert to the csl json; everything else dump in some `extra` object.

Well, we could just convert them to json, whether valid in CSL or not. Having non-spec data in there would not really do any harm.

**Comment by bdarcus** [comment]
> > So for all those keys that exist in CSL, but don't have dedicated fields in Zotero, convert to the csl json; everything else dump in some `extra` object.
> 
> Well, we could just convert them to json, whether valid in CSL or not. Having non-spec data in there would not really do any harm.

And I think that'd be fine too; has the advantage apps don't even need to know what a proper csl field is.

**Comment by bwiernik** [comment]
I'm reasonably optimistic about implementing things in Zotero, much less so in Mendeley. Don't really know about at all about Papers, ReadCube, etc.

**Comment by bwiernik** [comment]
> And I think that'd be fine too; has the advantage apps don't even need to know what a proper csl field is; just converting syntax.

One potential drawback is someone is storing something in `note` that they want to cite in `note` but which resembles a key-value pair.

**Comment by bwiernik** [comment]
So, for example, maybe a student is using apa-annotated-bibliography.csl, which uses `note` for the annotations, and the student has a structured annotation format like this:
```
Purpose: To test the hypothesis that chocolate is delicious.
Hypothesis: Only dark chocolate is delicious.
Design: Experimental
Sample size: 1000
```

We wouldn't want that to get sucked up and parsed into 4 new variables (purpose, hypothesis, design, sample-size). 

My vote would be for citeprocs to be responsible for parsing valid CSL data. If another application like @dhimmel wants to store and parse additional variables from `note`, then I'd say that its up to that application to parse out their own data for that purpose (e.g., BetterBibTeX in Zotero defines a system of fields starting with `tex.` to store arbitrary TeX data in Zotero's Extra, which is removes when CSL-JSON is generated).  

If we do want to provide encouragement for custom variables (which I really don't like), then a prefix like `csl:`, `csl.`, or `csl_` might differentiate variables intended to be CSL style variables versus other field content.

**Comment by retorquere** [comment]
Perhaps an extension to this idea: If there would be a general marker indicating "this line has a variable" but still having some kind of namespace, then applications processing such notes could reliably strip all variables while picking out for processing only those they know about; that way, the `tex.` variables would be removed in contexts where they make no sense while not cluttering up notes.

Not that I'd want to promote bringing back `{:var:value}`, but if we take that just as a way to think about it, `{tex.var: ...}` (and `{tex.var=...}` or {`tex.var*: ...}`) can reliably be stripped.

**Comment by bwiernik** [comment]
You're reawakening nightmares of `{:var:value}` 😜

I think maintaining human readability is important (that's why `CSL Variable: Value` took over from `{:var:value}`). Two potential options: 

1. For non-CSL variables intended to be variables, they should start with a namespace and be a key-value pair with a colon: `nsp.variable: value`.
1. For non-CSL variables, individual lines or the whole block should be wrapped in `{}`. So, for example:
```
{
tex.customa: value
tex.customb: value
}
```

**Comment by retorquere** [comment]
BBT needs at least a way to distinguish between `tex.var:` (text that still needs to be tex-ified) and `tex.var=` (raw latex to be passed to the output as-is). Whether that's `=` or something else doesn't really matter.

**Comment by dstillman** [comment]
While citeproc-js's `note` parsing has served us well, I don't see why this belongs in CSL. The CSL processor should be concerned with CSL variables, and it's the calling application's responsibility to provide them in a structured format.

As @bwiernik said, this was really just a hack to sync data between Zotero and MLZ/Juris-M. It did have the side effect of allowing citeproc-js to handle types and fields that Zotero didn't yet have, but even without new types and fields (which have been delayed for years for complicated technical reasons, hopefully soon resolved), Zotero could've been updated at any time to extract specific additional CSL variables from Extra and pass them to the processor itself. And that's exactly what we'd do if we switched to a different citation processor.

It's true that any application that uses citeproc-js has been able to take advantage of this hack, but I don't see why that's CSL's concern. The apps that use citeproc-js will likely continue to do so, and for new development it doesn't seem like CSL's job to dictate how an application should handle a temporary mismatch between its own data model and its citation processor. Ideally, an application would just avoid such a mismatch, but if it couldn't, one could certainly imagine cleaner, safer options than a free-form text field, or even different parsing rules out of a free-form text field that better fit the app's expected usage of that field. It seems like that's just a decision to be made between an app — be it GUI, CLI, or server-side — and its users.

**Comment by retorquere** [comment]
For the record: I did mean this to be pre-"pass to CSL" parsing that could be done by CSL-engine users moreso than the CSL engine itself, aside maybe the "CSL Variable: value" stuff. But even there I'd argue that what's now in Zotero's `extra` should not be passed to the CSL `note` field (at least not without filtering out all these variables, including the CSL variables), given that the CSL `note` field means:

> (short) inline note giving additional item details (e.g. a concise summary or commentary)

**Comment by bdarcus** [comment]
> While citeproc-js's `note` parsing has served us well, I don't see why this belongs in CSL. The CSL processor should be concerned with CSL variables, and it's the calling application's responsibility to provide them in a structured format.

So I vote we close this issue, and encourage (though not in the spec) Zotero et al to provide a a mechanism for users to generate valid csl input data.

If we want to document the hack, we can put it on one of the repo wikis.

I do think we should also add ability to include non-standard fields in the json; either in a new `extras` field, per @dhimmel, or by simply allowing optional keys. This gives applications a place to put their non-standard data.

**Comment by retorquere** [comment]
What would be the benefit of having them in a `extras` field which would require further parsing? It'd say have the `extras` field be a dict with perhaps indicators for type of the values. That would bring the whole thing into range for JSON-schema validation so that tools feeding data into citeproc could pre-flight their data before handover.

**Comment by bdarcus** [comment]
> What would be the benefit of having them in a `extras` field which would require further parsing?

Sorry; shouldn't have used that word "field."

Yes, it would be like [this](https://github.com/citation-style-language/documentation/issues/97#issuecomment-649666642)

**Comment by retorquere** [comment]
Ah OK, so something like

```
{
  ...
  "extras": {
    "my-field": "I can have anything here",
    "my-other-field": null
  }
}
```

would styles need to know whether `my-field` is a date, a creator, text, etc?

**Comment by bwiernik** [comment]
I'll reiterate my opinion that CSL should not accommodate non-CSL variables. A major strength of CSL compared to BibTeX, in my opinion, is the way it has not embraced user-specific data entry.

**Comment by bdarcus** [comment]
> Ah OK, so something like

Yes.

> would styles need to know whether `my-field` is a date, a creator, text, etc?

At this point, csl processors would ignore these data. So no.

I think whether to allow that in styles is a separate issue (and I am also skeptical, like @bwiernik), where we would have to answer the questions you pose. But I don't suggest we consider this now.

**Comment by bdarcus** [comment]
> If an application is storing custom data in CSL that shouldn't be rendered by other applications, it's their responsibility to remove it before exporting the CSL-JSON.

Why do we care what people or applications put in the input data, if we don't care what they embed in the note field in some non-standard syntax?

CSL JSON is being used for data exchange, and I certainly wouldn't want my custom data stripped from the output, even if it has no impact on citation processing. I might want to run a script on that output, for example, to generate some other output.

I think non-standard metadata only becomes a compatibility issue if we add it to the styling. And support for one does not = support for the other.

**Comment by dhimmel** [comment]
Great points everyone regarding custom / extra fields. I'm opening a new issue for this, so that we can keep discussion organized and focused. See https://github.com/citation-style-language/schema/issues/277.

**Comment by denismaier** [comment]
> CSL processors would ignore these data. So no.

I have had no time to read through this whole thread, but this an assumption has come up at least twice, and I think this is not the current behaviour.

Currently, citeproc-js happens to pick up every variable you throw at it, whether or not it is valid CSL. 
E.g. this test fixture here will pass:

```
>>===== MODE =====>>
citation
<<===== MODE =====<<



>>===== RESULT =====>>
A Title (content in a non-CSL variable)
<<===== RESULT =====<<


>>===== CSL =====>>
<style 
      xmlns="http://purl.org/net/xbiblio/csl"
      class="note"
      version="1.0">
  <info>
    <id />
    <title />
  </info>
  <citation>
    <layout>
      <group delimiter=" ">
        <text variable="title"/>
        <text variable="whatever" prefix="(" suffix=")"/>
      </group>
    </layout>
  </citation>
</style>
<<===== CSL =====<<


>>===== INPUT =====>>
[
    {
        "id": "ITEM-1", 
        "note": "whatever: content in a non-CSL variable", 
        "title": "A Title", 
        "type": "book"
    }
]
<<===== INPUT =====<<
```

Taking @bwiernik's example from above, you can even do this:

```
>>===== MODE =====>>
citation
<<===== MODE =====<<



>>===== RESULT =====>>
To test the hypothesis that chocolate is delicious.; Only dark chocolate is delicious.; Experimental; 1000
<<===== RESULT =====<<


>>===== CSL =====>>
<style 
      xmlns="http://purl.org/net/xbiblio/csl"
      class="note"
      version="1.0">
  <info>
    <id />
    <title />
  </info>
  <citation>
    <layout>
      <group delimiter="; ">
        <text variable="purpose"/>
        <text variable="hypothesis"/>
        <text variable="design"/>
        <text variable="sample-size"/>
      </group>
    </layout>
  </citation>
</style>
<<===== CSL =====<<


>>===== INPUT =====>>
[
    {
        "id": "ITEM-1", 
        "note": "purpose: To test the hypothesis that chocolate is delicious.\nhypothesis: Only dark chocolate is delicious.\ndesign: Experimental\nsample-size: 1000", 
        "title": "A Title", 
        "type": "book"
    }
]
<<===== INPUT =====<<
```

(Theoretically a simple `Sample size: 10000` should also work, but I had no success.)

**Comment by bdarcus** [comment]
That's a bug then ;-)

>

**Comment by denismaier** [comment]
> That's a bug then ;-)
> […](#)

Maybe... but that's how things stand since already a couple of years. (And it's quite nice since it allows you to follow niche rules.)
